// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from 'storyblok'
export interface GridStoryblok {
    columns?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    component: 'grid'
    _uid: string
    [k: string]: any
}

export interface AssetStoryblok {
    alt: string | null
    copyright?: string | null
    fieldtype: 'asset'
    id: number
    filename: string | null
    name: string
    title: string | null
    focus: string | null
    meta_data?: {
        [k: string]: any
    }
    source?: string | null
    is_external_url?: boolean
    is_private?: boolean
    src?: string
    updated_at?: string
    width?: number | null
    height?: number | null
    aspect_ratio?: number | null
    public_id?: string | null
    content_type?: string
    [k: string]: any
}

export interface TestimonialCardSlideStoryblok {
    content?: string
    author_title?: string
    author_subtitle?: string
    author_image?: AssetStoryblok
    component: 'testimonial-card-slide'
    _uid: string
    [k: string]: any
}

export interface MailingListFormStoryblok {
    heading?: string
    component: 'mailing-list-form'
    _uid: string
    [k: string]: any
}

export interface PortfolioGridStoryblok {
    grid_items?: PortfolioItemStoryblok[]
    portfolio_references?: GlobalReferenceStoryblok[]
    component: 'portfolio-grid'
    _uid: string
    [k: string]: any
}

export interface ContactSectionStoryblok {
    heading?: string
    subheading?: string
    form_fields?: (
        | ''
        | 'firstname'
        | 'lastname'
        | 'email'
        | 'linkedinUrl'
        | 'message'
        | 'pitchdeck'
        | 'roundsize'
        | 'sector'
        | 'pitchdeckUrl'
    )[]
    submitted_title?: string
    submitted_subtitle?: string
    component: 'contact-section'
    _uid: string
    [k: string]: any
}

export interface VenturePartnersStoryblok {
    heading?: string
    slides?: VenturePartnerStoryblok[]
    reference_slides?: GlobalReferenceStoryblok[]
    component: 'venture-partners'
    _uid: string
    [k: string]: any
}

export interface TeaserStoryblok {
    headline?: string
    component: 'teaser'
    _uid: string
    [k: string]: any
}

export interface GlobalReferenceStoryblok {
    reference?: any[]
    component: 'global_reference'
    _uid: string
    [k: string]: any
}

export type MultilinkStoryblok =
    | {
          fieldtype: 'multilink'
          id: string
          url: string
          cached_url: string
          target?: '_blank' | '_self'
          anchor?: string
          rel?: string
          title?: string
          prep?: string
          linktype: 'story'
          story?: {
              name: string
              created_at?: string
              published_at?: string
              id: number
              uuid: string
              content?: {
                  [k: string]: any
              }
              slug: string
              full_slug: string
              sort_by_date?: null | string
              position?: number
              tag_list?: string[]
              is_startpage?: boolean
              parent_id?: null | number
              meta_data?: null | {
                  [k: string]: any
              }
              group_id?: string
              first_published_at?: string
              release_id?: null | number
              lang?: string
              path?: null | string
              alternates?: any[]
              default_full_slug?: null | string
              translated_slugs?: null | any[]
              [k: string]: any
          }
          [k: string]: any
      }
    | {
          fieldtype: 'multilink'
          id: string
          url: string
          cached_url: string
          target?: '_blank' | '_self'
          linktype: 'url'
          rel?: string
          title?: string
          [k: string]: any
      }
    | {
          fieldtype: 'multilink'
          id: string
          url: string
          cached_url: string
          target?: '_blank' | '_self'
          email?: string
          linktype: 'email'
          [k: string]: any
      }
    | {
          fieldtype: 'multilink'
          id: string
          url: string
          cached_url: string
          target?: '_blank' | '_self'
          linktype: 'asset'
          [k: string]: any
      }

export interface HeadingWithMediaStoryblok {
    media?: AssetStoryblok
    video?: AssetStoryblok
    heading?: string
    description?: string
    link_text?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    order?: boolean
    component: 'heading-with-media'
    _uid: string
    [k: string]: any
}

export interface GlobalStoryblok {
    global?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    component: 'global'
    _uid: string
    [k: string]: any
}

export interface MainHeroStoryblok {
    logo?: AssetStoryblok
    component: 'main-hero'
    _uid: string
    [k: string]: any
}

export interface TextSlideStoryblok {
    heading?: string
    description?: string
    component: 'text-slide'
    _uid: string
    [k: string]: any
}

export interface ColorSchemeStoryblok {
    background?: string
    foreground?: string
    component: 'color-scheme'
    _uid: string
    [k: string]: any
}

export type MultiassetStoryblok = {
    alt: string | null
    copyright?: string | null
    fieldtype: 'asset'
    id: number
    filename: string | null
    name: string
    title: string | null
    focus: string | null
    meta_data?: {
        [k: string]: any
    }
    source?: string | null
    is_external_url?: boolean
    is_private?: boolean
    src?: string
    updated_at?: string
    width?: number | null
    height?: number | null
    aspect_ratio?: number | null
    public_id?: string | null
    content_type?: string
    [k: string]: any
}[]

export interface HeadingWithCarouselStoryblok {
    heading?: string
    description?: string
    link_text?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    order?: boolean
    carousel_height?: string
    carousel_width?: string
    Images?: MultiassetStoryblok
    loop?: boolean
    component: 'heading-with-carousel'
    _uid: string
    [k: string]: any
}

export interface PostTagStoryblok {
    name?: string
    component: 'post_tag'
    _uid: string
    [k: string]: any
}

export interface PageStoryblok {
    body?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    component: 'page'
    _uid: string
    [k: string]: any
}

export interface MemberSlideStoryblok {
    name: string
    profession?: string
    description?: string
    image: AssetStoryblok
    component: 'member-slide'
    _uid: string
    [k: string]: any
}

export interface PortfolioCarouselStoryblok {
    heading?: string
    slides?: (MediaWithTextSlideStoryblok | GlobalReferenceStoryblok)[]
    mobile_view?: MobileDescLinkStoryblok[]
    component: 'portfolio-carousel'
    _uid: string
    [k: string]: any
}

export interface TimeTagMediaSlideStoryblok {
    heading?: string
    date?: string
    media?: AssetStoryblok
    tags?: PostTagStoryblok[]
    component: 'time-tag-media-slide'
    _uid: string
    [k: string]: any
}

export interface RichtextStoryblok {
    type: string
    content?: RichtextStoryblok[]
    marks?: RichtextStoryblok[]
    attrs?: any
    text?: string
    [k: string]: any
}

export interface PortfolioItemStoryblok {
    company_name: string
    brand_logo?: AssetStoryblok
    logo_height?: string
    mobile_logo_height?: string
    company_description?: RichtextStoryblok
    featured_image?: AssetStoryblok
    company_link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    component: 'portfolio_item'
    _uid: string
    [k: string]: any
}

export interface MediaWithTextSlideStoryblok {
    heading?: string
    description?: RichtextStoryblok
    image?: AssetStoryblok
    component: 'media-with-text-slide'
    _uid: string
    [k: string]: any
}

export interface ZigzagApproachStoryblok {
    heading?: string
    background_color?: string
    foreground_color?: string
    accordion?: AccordionBlockStoryblok[]
    top_spacing?: string
    bottom_spacing?: string
    mobile_top_spacing?: string
    mobile_bottom_spacing?: string
    component: 'zigzag-approach'
    _uid: string
    [k: string]: any
}

export interface PortfolioGridItemStoryblok {
    brand_logo?: AssetStoryblok
    image?: AssetStoryblok
    description?: string
    link_text?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    component: 'portfolio-grid-item'
    _uid: string
    [k: string]: any
}

export interface CalloutSectionStoryblok {
    heading?: string
    subheading?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    link_label?: string
    component: 'callout-section'
    _uid: string
    [k: string]: any
}

export interface NavLinkStoryblok {
    Name: string
    link: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    open_in_new_tab?: boolean
    component: 'NavLink'
    _uid: string
    [k: string]: any
}

export interface VenturePartnerStoryblok {
    image?: AssetStoryblok
    name: string
    profession?: string
    about?: RichtextStoryblok
    url?: Exclude<MultilinkStoryblok, { linktype?: 'asset' }>
    component: 'venturePartner'
    _uid: string
    [k: string]: any
}

export interface TextCardsCarouselStoryblok {
    slides?: TextSlideStoryblok[]
    component: 'text-cards-carousel'
    _uid: string
    [k: string]: any
}

export interface MobileDescLinkStoryblok {
    description?: string
    link_text?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    component: 'mobile_desc_link'
    _uid: string
    [k: string]: any
}

export interface MarqueeBlockStoryblok {
    marquee_text?: string
    component: 'marquee_block'
    _uid: string
    [k: string]: any
}

export interface KeyThemeSlideStoryblok {
    heading?: string
    image?: AssetStoryblok
    background_color?: string
    component: 'key-theme-slide'
    _uid: string
    [k: string]: any
}

export interface TestimonialCarouselSlideStoryblok {
    heading_line_1?: string
    heading_line_2?: string
    description?: string
    image?: AssetStoryblok
    component: 'testimonial-carousel-slide'
    _uid: string
    [k: string]: any
}

export interface PostStoryblok {
    featured_image?: AssetStoryblok
    published_at: string
    updated_at?: string
    author?: any[]
    title?: string
    description?: string
    synopsis?: string
    content?: RichtextStoryblok
    component: 'post'
    _uid: string
    [k: string]: any
}

export interface PortfolioImageWithTextStoryblok {
    items?: ImageWithTextStoryblok[]
    component: 'portfolio-image-with-text'
    _uid: string
    [k: string]: any
}

export interface HeaderStoryblok {
    title?: string
    logo?: AssetStoryblok
    small_logo_icon?: AssetStoryblok
    show_small_icon?: boolean
    mobile_logo: AssetStoryblok
    navbar?: NavLinkStoryblok[]
    drawer?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    component: 'header'
    _uid: string
    [k: string]: any
}

export interface OurApproachStoryblok {
    heading?: string
    background_color?: string
    foreground_color?: string
    accordion?: AccordionBlockStoryblok[]
    image?: AssetStoryblok
    content_padding?: boolean
    hide_last_border?: boolean
    top_spacing?: string
    bottom_spacing?: string
    mobile_top_spacing?: string
    mobile_bottom_spacing?: string
    component: 'our-approach'
    _uid: string
    [k: string]: any
}

export interface ImageWithTextStoryblok {
    brand_logo?: AssetStoryblok
    description?: string
    link_text?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    image?: AssetStoryblok
    order?: boolean
    component: 'image-with-text'
    _uid: string
    [k: string]: any
}

export interface PostsListStoryblok {
    component: 'posts-list'
    _uid: string
    [k: string]: any
}

export interface PerspectivesCarouselStoryblok {
    heading?: string
    nav_link?: NavLinkStoryblok[]
    mobile_view?: MobileDescLinkStoryblok[]
    auto_fetch_posts?: boolean
    slides?: (TimeTagMediaSlideStoryblok | GlobalReferenceStoryblok)[]
    component: 'perspectives-carousel'
    _uid: string
    [k: string]: any
}

export interface TableStoryblok {
    thead: {
        _uid: string
        value?: string
        component: number
        [k: string]: any
    }[]
    tbody: {
        _uid: string
        body: {
            _uid?: string
            value?: string
            component?: number
            [k: string]: any
        }[]
        component: number
        [k: string]: any
    }[]
    [k: string]: any
}

export interface BusinessLevelStoryblok {
    business_heading?: string
    business_features?: TableStoryblok
    component: 'business-level'
    _uid: string
    [k: string]: any
}

export interface BannerLinkStoryblok {
    heading?: string
    description?: string
    link?: Exclude<
        MultilinkStoryblok,
        { linktype?: 'email' } | { linktype?: 'asset' }
    >
    link_text?: string
    component: 'banner-link'
    _uid: string
    [k: string]: any
}

export interface FeatureStoryblok {
    name?: string
    navbar?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    logo?: AssetStoryblok
    component: 'feature'
    _uid: string
    [k: string]: any
}

export interface BigTextMarqueeStoryblok {
    marquee_blocks?: MarqueeBlockStoryblok[]
    component: 'big-text-marquee'
    _uid: string
    [k: string]: any
}

export interface TestimonialsCardCarouselStoryblok {
    heading?: string
    slides?: TestimonialCardSlideStoryblok[]
    component: 'testimonials-card-carousel'
    _uid: string
    [k: string]: any
}

export interface KeyThemesStoryblok {
    heading?: string
    heading_alignment?: '' | 'start' | 'center' | 'end'
    slides?: KeyThemeSlideStoryblok[]
    component: 'key-themes'
    _uid: string
    [k: string]: any
}

export interface FooterStoryblok {
    title?: string
    logo?: AssetStoryblok
    mobile_logo?: AssetStoryblok
    navbar?: (
        | GridStoryblok
        | TestimonialCardSlideStoryblok
        | MailingListFormStoryblok
        | PortfolioGridStoryblok
        | ContactSectionStoryblok
        | VenturePartnersStoryblok
        | TeaserStoryblok
        | GlobalReferenceStoryblok
        | HeadingWithMediaStoryblok
        | GlobalStoryblok
        | MainHeroStoryblok
        | TextSlideStoryblok
        | ColorSchemeStoryblok
        | HeadingWithCarouselStoryblok
        | PostTagStoryblok
        | PageStoryblok
        | MemberSlideStoryblok
        | PortfolioCarouselStoryblok
        | TimeTagMediaSlideStoryblok
        | PortfolioItemStoryblok
        | MediaWithTextSlideStoryblok
        | ZigzagApproachStoryblok
        | PortfolioGridItemStoryblok
        | CalloutSectionStoryblok
        | NavLinkStoryblok
        | VenturePartnerStoryblok
        | TextCardsCarouselStoryblok
        | MobileDescLinkStoryblok
        | MarqueeBlockStoryblok
        | KeyThemeSlideStoryblok
        | TestimonialCarouselSlideStoryblok
        | PostStoryblok
        | PortfolioImageWithTextStoryblok
        | HeaderStoryblok
        | OurApproachStoryblok
        | ImageWithTextStoryblok
        | PostsListStoryblok
        | PerspectivesCarouselStoryblok
        | BusinessLevelStoryblok
        | BannerLinkStoryblok
        | FeatureStoryblok
        | BigTextMarqueeStoryblok
        | TestimonialsCardCarouselStoryblok
        | KeyThemesStoryblok
        | FooterStoryblok
        | HeaderDrawerStoryblok
        | TeamMemberStoryblok
        | SecondaryHeroStoryblok
        | BusinessOperationsStoryblok
        | TestimonialsCarouselStoryblok
        | TeamMembersStoryblok
        | AccordionBlockStoryblok
    )[]
    copyright_text?: RichtextStoryblok
    secondary_variant?: boolean
    secondary_symbol?: AssetStoryblok
    description?: string
    secondary_logo?: AssetStoryblok
    component: 'footer'
    _uid: string
    [k: string]: any
}

export interface HeaderDrawerStoryblok {
    links?: NavLinkStoryblok[]
    copyright_text?: RichtextStoryblok
    component: 'header-drawer'
    _uid: string
    [k: string]: any
}

export interface TeamMemberStoryblok {
    image?: AssetStoryblok
    name?: string
    profession?: string
    description?: string
    url?: Exclude<MultilinkStoryblok, { linktype?: 'asset' }>
    component: 'team-member'
    _uid: string
    [k: string]: any
}

export interface SecondaryHeroStoryblok {
    heading?: string
    subheading?: string
    heading_alignment?: '' | 'start' | 'center' | 'end'
    subheading_alignment?: '' | 'start' | 'center' | 'end'
    top_spacing?: string
    bottom_spacing?: string
    mobile_top_spacing?: string
    mobile_bottom_spacing?: string
    component: 'secondary-hero'
    _uid: string
    [k: string]: any
}

export interface BusinessOperationsStoryblok {
    heading?: string
    component: 'business-operations'
    _uid: string
    [k: string]: any
}

export interface TestimonialsCarouselStoryblok {
    slides?: TestimonialCarouselSlideStoryblok[]
    component: 'testimonials-carousel'
    _uid: string
    [k: string]: any
}

export interface TeamMembersStoryblok {
    slides?: MemberSlideStoryblok[]
    reference_slide?: GlobalReferenceStoryblok[]
    component: 'team-members'
    _uid: string
    [k: string]: any
}

export interface AccordionBlockStoryblok {
    title?: string
    content?: string
    component: 'accordion-block'
    _uid: string
    [k: string]: any
}
