import {
    BannerLink,
    BigTextMarquee,
    BusinessOperations,
    CalloutSection,
    ContactSection,
    Footer,
    Global,
    Header,
    HeadingCarousel,
    HeadingWithMedia,
    KeyThemes,
    MailingListForm,
    MainHero,
    OurApproach,
    Page,
    Post,
    PerspectivesCarousel,
    PortfolioCarousel,
    PortfolioGrid,
    PortfolioImageWithText,
    PostsList,
    SecondaryHero,
    TeamMembers,
    TestimonialsCarousel,
    TextCardsCarousel,
    VenturePartners,
} from '@/components/index'
import TestimonialsCardCarousel from '@/components/TestimonialsCardCarousel'
import { ZigzagApproach } from '@/components/ZigzagApproach'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'

export function initStoryblokClient() {
    storyblokInit({
        accessToken: process.env.STORYBLOK_ACCESS_TOKEN,
        use: [apiPlugin],
        apiOptions: {
            region: process.env.STORYBLOK_REGION,
        },
        components: {
            page: Page,
            post: Post,
            global: Global,
            header: Header,
            footer: Footer,
            'main-hero': MainHero,
            'secondary-hero': SecondaryHero,
            'key-themes': KeyThemes,
            'contact-section': ContactSection,
            'callout-section': CalloutSection,
            'business-operations': BusinessOperations,
            'team-members': TeamMembers,
            'venture-partners': VenturePartners,
            'our-approach': OurApproach,
            'big-text-marquee': BigTextMarquee,
            'perspectives-carousel': PerspectivesCarousel,
            'portfolio-carousel': PortfolioCarousel,
            'text-cards-carousel': TextCardsCarousel,
            'banner-link': BannerLink,
            'heading-with-carousel': HeadingCarousel,
            'posts-list': PostsList,
            'mailing-list-form': MailingListForm,
            'testimonials-carousel': TestimonialsCarousel,
            'portfolio-grid': PortfolioGrid,
            'heading-with-media': HeadingWithMedia,
            'portfolio-image-with-text': PortfolioImageWithText,
            'testimonials-card-carousel': TestimonialsCardCarousel,
            'zigzag-approach': ZigzagApproach,
        },
    })
}
